# Generated by Django 4.2.23 on 2025-06-16 22:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("dashboard", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="GuiaAutocontrol",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("titulo_guia", models.CharField(blank=True, max_length=300)),
                ("componente", models.CharField(blank=True, max_length=200)),
                ("proposito", models.TextField(blank=True)),
                ("contenido_procesado", models.JSONField(blank=True, default=dict)),
                ("activa", models.BooleanField(default=True)),
                ("fecha_procesamiento", models.DateTimeField(auto_now=True)),
                (
                    "archivo",
                    models.OneToOneField(
                        limit_choices_to={"es_formulario": True},
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="guia_autocontrol",
                        to="dashboard.archivo",
                    ),
                ),
            ],
            options={
                "verbose_name": "Guía de Autocontrol",
                "verbose_name_plural": "Guías de Autocontrol",
                "ordering": ["-fecha_procesamiento"],
            },
        ),
        migrations.CreateModel(
            name="EvaluacionGuia",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fecha_inicio", models.DateTimeField(auto_now_add=True)),
                ("fecha_completado", models.DateTimeField(blank=True, null=True)),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("no_iniciada", "No Iniciada"),
                            ("en_progreso", "En Progreso"),
                            ("completada", "Completada"),
                            ("revisada", "Revisada"),
                        ],
                        default="no_iniciada",
                        max_length=20,
                    ),
                ),
                (
                    "porcentaje_cumplimiento",
                    models.DecimalField(
                        decimal_places=2,
                        default=0.0,
                        max_digits=5,
                        verbose_name="Porcentaje de Cumplimiento",
                    ),
                ),
                (
                    "comentarios",
                    models.TextField(
                        blank=True, verbose_name="Observaciones Generales"
                    ),
                ),
                (
                    "guia",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="evaluaciones",
                        to="guia.guiaautocontrol",
                        verbose_name="Guía",
                    ),
                ),
                (
                    "usuario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="evaluaciones_guias",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Usuario",
                    ),
                ),
            ],
            options={
                "verbose_name": "Evaluación de Guía",
                "verbose_name_plural": "Evaluaciones de Guías",
                "ordering": ["-fecha_inicio"],
                "unique_together": {("guia", "usuario")},
            },
        ),
        migrations.CreateModel(
            name="RespuestaGuia",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "numero_pregunta",
                    models.IntegerField(verbose_name="Número de Pregunta"),
                ),
                (
                    "respuesta",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("si", "Sí"),
                            ("no", "No"),
                            ("na", "No Aplica"),
                            (None, "Sin Responder"),
                        ],
                        max_length=3,
                        null=True,
                        verbose_name="Respuesta",
                    ),
                ),
                (
                    "fundamentacion",
                    models.TextField(blank=True, verbose_name="Fundamentación"),
                ),
                (
                    "fecha_respuesta",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Fecha de Respuesta"
                    ),
                ),
                (
                    "evaluacion",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="respuestas",
                        to="guia.evaluacionguia",
                        verbose_name="Evaluación",
                    ),
                ),
            ],
            options={
                "verbose_name": "Respuesta de Guía",
                "verbose_name_plural": "Respuestas de Guías",
                "ordering": ["evaluacion__guia__titulo_guia", "numero_pregunta"],
                "unique_together": {("evaluacion", "numero_pregunta")},
            },
        ),
    ]
