# Generated by Django 4.2.23 on 2025-07-02 19:12

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("dashboard", "0002_remove_comentario_autor_remove_comentario_post_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="GuiaAutocontrol",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("titulo_guia", models.CharField(blank=True, max_length=300)),
                ("componente", models.CharField(blank=True, max_length=200)),
                ("proposito", models.TextField(blank=True)),
                ("contenido_procesado", models.JSONField(blank=True, default=dict)),
                ("activa", models.BooleanField(default=True)),
                ("fecha_procesamiento", models.DateTimeField(auto_now=True)),
                (
                    "hash_archivo",
                    models.CharField(blank=True, editable=False, max_length=64),
                ),
                ("version", models.CharField(blank=True, max_length=20)),
                (
                    "total_preguntas",
                    models.PositiveIntegerField(default=0, editable=False),
                ),
                (
                    "categorias_count",
                    models.PositiveIntegerField(default=0, editable=False),
                ),
                (
                    "archivo",
                    models.OneToOneField(
                        limit_choices_to={"es_formulario": True},
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="guia_autocontrol",
                        to="dashboard.archivo",
                    ),
                ),
            ],
            options={
                "verbose_name": "Guía de Autocontrol",
                "verbose_name_plural": "Guías de Autocontrol",
                "ordering": ["-fecha_procesamiento"],
            },
        ),
        migrations.CreateModel(
            name="EvaluacionGuia",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fecha_inicio", models.DateTimeField(auto_now_add=True)),
                ("fecha_completado", models.DateTimeField(blank=True, null=True)),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("no_iniciada", "No Iniciada"),
                            ("en_progreso", "En Progreso"),
                            ("completada", "Completada"),
                            ("revisada", "Revisada"),
                        ],
                        default="no_iniciada",
                        max_length=20,
                    ),
                ),
                (
                    "porcentaje_cumplimiento",
                    models.DecimalField(
                        decimal_places=2,
                        default=0.0,
                        max_digits=5,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                    ),
                ),
                ("comentarios", models.TextField(blank=True)),
                ("total_respuestas", models.PositiveIntegerField(default=0)),
                ("respuestas_si", models.PositiveIntegerField(default=0)),
                ("respuestas_no", models.PositiveIntegerField(default=0)),
                ("respuestas_na", models.PositiveIntegerField(default=0)),
                (
                    "guia",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="evaluaciones",
                        to="guia.guiaautocontrol",
                    ),
                ),
                (
                    "usuario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="evaluaciones_guias",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Evaluación de Guía",
                "ordering": ["-fecha_inicio"],
            },
        ),
        migrations.CreateModel(
            name="RespuestaGuia",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("numero_pregunta", models.IntegerField()),
                (
                    "respuesta",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("si", "Sí"),
                            ("no", "No"),
                            ("na", "No Aplica"),
                            ("", "Sin Responder"),
                        ],
                        default="",
                        max_length=4,
                        null=True,
                    ),
                ),
                ("fundamentacion", models.TextField(blank=True)),
                ("fecha_respuesta", models.DateTimeField(auto_now=True)),
                ("fecha_modificacion", models.DateTimeField(auto_now=True)),
                (
                    "evidencias",
                    models.ManyToManyField(blank=True, to="dashboard.archivo"),
                ),
                (
                    "guia",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="guia.guiaautocontrol",
                    ),
                ),
                (
                    "usuario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Respuesta de Guía",
                "ordering": ["guia_id", "numero_pregunta"],
                "indexes": [
                    models.Index(
                        fields=["guia", "usuario"],
                        name="guia_respue_guia_id_fc0abf_idx",
                    ),
                    models.Index(
                        fields=["numero_pregunta"],
                        name="guia_respue_numero__a16540_idx",
                    ),
                    models.Index(
                        fields=["respuesta"], name="guia_respue_respues_21bd82_idx"
                    ),
                ],
                "unique_together": {("guia", "usuario", "numero_pregunta")},
            },
        ),
        migrations.AddIndex(
            model_name="guiaautocontrol",
            index=models.Index(
                fields=["componente"], name="guia_guiaau_compone_e9101e_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="guiaautocontrol",
            index=models.Index(
                fields=["activa", "fecha_procesamiento"],
                name="guia_guiaau_activa_2d30ea_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="guiaautocontrol",
            index=models.Index(
                fields=["total_preguntas"], name="guia_guiaau_total_p_7faf52_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="evaluacionguia",
            index=models.Index(fields=["estado"], name="guia_evalua_estado_f4106f_idx"),
        ),
        migrations.AddIndex(
            model_name="evaluacionguia",
            index=models.Index(
                fields=["porcentaje_cumplimiento"],
                name="guia_evalua_porcent_b40c55_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="evaluacionguia",
            index=models.Index(
                fields=["guia", "usuario"], name="guia_evalua_guia_id_fbdfa9_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="evaluacionguia",
            unique_together={("guia", "usuario")},
        ),
    ]
