# Generated by Django 4.2.23 on 2025-06-29 00:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="post",
            name="categoria",
        ),
        migrations.DeleteModel(
            name="Categoria",
        ),
    ]
