# Generated by Django 5.2.1 on 2025-06-09 13:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EnlaceInteres',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200, verbose_name='Título')),
                ('url', models.URLField(verbose_name='URL')),
                ('descripcion', models.TextField(blank=True, verbose_name='Descripción')),
                ('categoria', models.CharField(blank=True, choices=[('', 'Sin categoría'), ('educativo', 'Educativo'), ('institucional', 'Institucional'), ('recursos', 'Recursos'), ('herramientas', 'Herramientas'), ('noticias', 'Noticias'), ('otros', 'Otros')], max_length=20, verbose_name='Categoría')),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='enlaces/', verbose_name='Imagen')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
                ('es_destacado', models.BooleanField(default=False, verbose_name='Destacado')),
                ('orden', models.IntegerField(default=0, verbose_name='Orden')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('fecha_modificacion', models.DateTimeField(auto_now=True, verbose_name='Fecha de modificación')),
                ('creado_por', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
            ],
            options={
                'verbose_name': 'Enlace de Interés',
                'verbose_name_plural': 'Enlaces de Interés',
                'ordering': ['-es_destacado', 'orden', '-fecha_creacion'],
            },
        ),
    ]
