# Generated by Django 4.2.23 on 2025-07-02 19:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="comentario",
            name="autor",
        ),
        migrations.RemoveField(
            model_name="comentario",
            name="post",
        ),
        migrations.RemoveField(
            model_name="post",
            name="autor",
        ),
        migrations.RemoveField(
            model_name="post",
            name="categoria",
        ),
        migrations.DeleteModel(
            name="Categoria",
        ),
        migrations.DeleteModel(
            name="Comentario",
        ),
        migrations.DeleteModel(
            name="Post",
        ),
    ]
