# Generated by Django 5.2.1 on 2025-06-09 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_enlaceinteres'),
    ]

    operations = [
        migrations.AddField(
            model_name='archivo',
            name='es_formulario',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='archivo',
            name='tipo',
            field=models.CharField(choices=[('imagen', 'Imagen'), ('documento', 'Documento'), ('video', 'Video'), ('pdf', 'PDF'), ('otro', 'Otro')], max_length=20),
        ),
    ]
