# Generated by Django 4.2.23 on 2025-06-30 04:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0002_remove_post_categoria_delete_categoria"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="post",
            name="autor",
        ),
        migrations.DeleteModel(
            name="Comentario",
        ),
        migrations.DeleteModel(
            name="Post",
        ),
    ]
