# Generated by Django 4.2.23 on 2025-06-28 21:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Categoria",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=100, unique=True)),
                ("slug", models.SlugField(max_length=100, unique=True)),
                ("descripcion", models.TextField(blank=True)),
                ("color", models.CharField(default="#007bff", max_length=7)),
                ("icono", models.CharField(blank=True, max_length=50)),
                ("activa", models.BooleanField(default=True)),
                ("fecha_creacion", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Categoría",
                "verbose_name_plural": "Categorías",
                "ordering": ["nombre"],
            },
        ),
        migrations.CreateModel(
            name="Post",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("titulo", models.CharField(max_length=200)),
                ("slug", models.SlugField(blank=True, max_length=200, unique=True)),
                ("contenido", models.TextField()),
                ("resumen", models.TextField(blank=True, max_length=300)),
                (
                    "imagen_destacada",
                    models.ImageField(blank=True, null=True, upload_to="posts/"),
                ),
                (
                    "fecha_creacion",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("fecha_actualizacion", models.DateTimeField(auto_now=True)),
                ("fecha_publicacion", models.DateTimeField(blank=True, null=True)),
                ("publicado", models.BooleanField(default=False)),
                ("destacado", models.BooleanField(default=False)),
                ("vistas", models.PositiveIntegerField(default=0)),
                ("likes", models.PositiveIntegerField(default=0)),
                ("meta_descripcion", models.CharField(blank=True, max_length=160)),
                ("meta_keywords", models.CharField(blank=True, max_length=255)),
                (
                    "autor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "categorias",
                    models.ManyToManyField(blank=True, to="usuarios.categoria"),
                ),
            ],
            options={
                "verbose_name": "Post",
                "verbose_name_plural": "Posts",
                "ordering": ["-fecha_creacion"],
            },
        ),
        migrations.CreateModel(
            name="Perfil",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "telefono",
                    models.CharField(
                        blank=True,
                        help_text="Número de teléfono del usuario",
                        max_length=20,
                    ),
                ),
                (
                    "cede",
                    models.IntegerField(
                        blank=True,
                        choices=[
                            (1, "Oscar Lucero Moya"),
                            (2, "Celia Sánchez Manduley"),
                            (3, "José de la Luz y Caballero"),
                        ],
                        null=True,
                        verbose_name="Cedes",
                    ),
                ),
                ("cargo", models.CharField(help_text="Cargo que ocupa", max_length=50)),
                (
                    "recibir_notificaciones",
                    models.BooleanField(
                        default=True,
                        help_text="Si el usuario desea recibir notificaciones por email",
                    ),
                ),
                (
                    "es_moderador",
                    models.BooleanField(
                        default=False,
                        help_text="Si el usuario tiene permisos de moderador",
                    ),
                ),
                (
                    "es_admin",
                    models.BooleanField(
                        default=False,
                        help_text="Si el usuario tiene permisos de administrador",
                    ),
                ),
                (
                    "puede_editar",
                    models.BooleanField(
                        default=False, help_text="Si el usuario puede editar contenido"
                    ),
                ),
                ("fecha_creacion", models.DateTimeField(auto_now_add=True)),
                ("last_activity", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="perfil",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Perfil",
                "verbose_name_plural": "Perfiles",
                "ordering": ["-fecha_creacion"],
            },
        ),
        migrations.CreateModel(
            name="Comentario",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("contenido", models.TextField()),
                (
                    "fecha_creacion",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("aprobado", models.BooleanField(default=True)),
                ("activo", models.BooleanField(default=True)),
                (
                    "autor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "padre",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="respuestas",
                        to="usuarios.comentario",
                    ),
                ),
                (
                    "post",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="comentarios",
                        to="usuarios.post",
                    ),
                ),
            ],
            options={
                "verbose_name": "Comentario",
                "verbose_name_plural": "Comentarios",
                "ordering": ["-fecha_creacion"],
            },
        ),
        migrations.CreateModel(
            name="Archivo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=255)),
                ("archivo", models.FileField(upload_to="uploads/")),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("imagen", "Imagen"),
                            ("documento", "Documento"),
                            ("video", "Video"),
                            ("audio", "Audio"),
                            ("otro", "Otro"),
                        ],
                        default="otro",
                        max_length=20,
                    ),
                ),
                ("descripcion", models.TextField(blank=True)),
                (
                    "fecha_subida",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("tamaño", models.PositiveIntegerField(default=0)),
                ("extension", models.CharField(blank=True, max_length=10)),
                ("publico", models.BooleanField(default=False)),
                (
                    "usuario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Archivo",
                "verbose_name_plural": "Archivos",
                "ordering": ["-fecha_subida"],
            },
        ),
    ]
