# Generated by Django 5.2.1 on 2025-06-08 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfil',
            name='cede',
            field=models.IntegerField(blank=True, choices=[(1, 'Oscar Lucero Moya'), (2, 'Celia Sánchez Manduley'), (3, 'José de la Luz y Caballero')], null=True, verbose_name='Cedes'),
        ),
    ]
