# Generated by Django 4.2.23 on 2025-07-02 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("usuarios", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="comentario",
            name="autor",
        ),
        migrations.RemoveField(
            model_name="comentario",
            name="padre",
        ),
        migrations.RemoveField(
            model_name="comentario",
            name="post",
        ),
        migrations.RemoveField(
            model_name="post",
            name="autor",
        ),
        migrations.RemoveField(
            model_name="post",
            name="categorias",
        ),
        migrations.AddField(
            model_name="perfil",
            name="firma_digital",
            field=models.FileField(blank=True, null=True, upload_to="firmas/"),
        ),
        migrations.DeleteModel(
            name="Categoria",
        ),
        migrations.DeleteModel(
            name="Comentario",
        ),
        migrations.DeleteModel(
            name="Post",
        ),
    ]
