# Generated by Django 4.2.23 on 2025-06-28 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("usuarios", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="perfil",
            name="firma_digital",
            field=models.FileField(blank=True, null=True, upload_to="firmas/"),
        ),
    ]
