# Generated by Django 4.2.23 on 2025-06-30 04:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("usuarios", "0002_perfil_firma_digital"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="comentario",
            name="autor",
        ),
        migrations.RemoveField(
            model_name="comentario",
            name="padre",
        ),
        migrations.RemoveField(
            model_name="comentario",
            name="post",
        ),
        migrations.RemoveField(
            model_name="post",
            name="autor",
        ),
        migrations.RemoveField(
            model_name="post",
            name="categorias",
        ),
        migrations.DeleteModel(
            name="Categoria",
        ),
        migrations.DeleteModel(
            name="Comentario",
        ),
        migrations.DeleteModel(
            name="Post",
        ),
    ]
