# Generated by Django 5.2.1 on 2025-06-07 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_categoria_rename_activo_perfil_perfil_publico_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfil',
            name='last_activity',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
