# Generated by Django 4.2.23 on 2025-08-05 21:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("usuarios", "0002_remove_comentario_autor_remove_comentario_padre_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="perfil",
            name="recovery_code",
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name="perfil",
            name="recovery_code_expiry",
            field=models.DateTimeField(
                blank=True,
                help_text="Fecha de expiración del código de recuperación",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="perfil",
            name="recovery_code_used",
            field=models.BooleanField(
                default=False,
                help_text="Indica si el código de recuperación ya fue usado",
            ),
        ),
        migrations.CreateModel(
            name="PasswordResetAudit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("action", models.CharField(max_length=20)),
                ("ip", models.GenericIPAddressField(blank=True, null=True)),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
